/**
 * Builds a Telegram-shaped sample update for route/destination testing.
 *
 * The payload is clearly marked as synthetic (`gateway_test: true` inside the update and
 * `gateway.test: true` in the envelope) so a downstream service can never mistake it for
 * a real Telegram event.
 */
export function buildSampleUpdate(eventType: string, botName: string): Record<string, unknown> {
  const now = Math.floor(Date.now() / 1000);
  // Negative update_id keeps synthetic events from colliding with real Telegram ids.
  const updateId = -Math.floor(Math.random() * 1_000_000_000);

  const from = {
    id: 100000001,
    is_bot: false,
    first_name: 'Gateway',
    last_name: 'Test',
    username: 'gateway_test',
    language_code: 'en',
  };
  const chat = { id: 100000001, first_name: 'Gateway', username: 'gateway_test', type: 'private' };

  const message = {
    message_id: 1,
    from,
    chat,
    date: now,
    text: `Test ${eventType} event from ${botName}`,
  };

  const bodies: Record<string, unknown> = {
    message,
    edited_message: { ...message, edit_date: now },
    channel_post: { ...message, chat: { ...chat, type: 'channel', title: 'Test channel' } },
    edited_channel_post: {
      ...message,
      edit_date: now,
      chat: { ...chat, type: 'channel', title: 'Test channel' },
    },
    callback_query: {
      id: 'test-callback-1',
      from,
      message,
      chat_instance: 'test-chat-instance',
      data: 'gateway_test',
    },
    inline_query: { id: 'test-inline-1', from, query: 'gateway test', offset: '' },
    chosen_inline_result: { result_id: 'r1', from, query: 'gateway test' },
    shipping_query: {
      id: 'test-shipping-1',
      from,
      invoice_payload: 'test',
      shipping_address: {
        country_code: 'DE',
        state: '',
        city: 'Berlin',
        street_line1: 'Test 1',
        street_line2: '',
        post_code: '10115',
      },
    },
    pre_checkout_query: {
      id: 'test-precheckout-1',
      from,
      currency: 'EUR',
      total_amount: 100,
      invoice_payload: 'test',
    },
    poll: {
      id: 'test-poll-1',
      question: 'Test?',
      options: [
        { text: 'Yes', voter_count: 1 },
        { text: 'No', voter_count: 0 },
      ],
      total_voter_count: 1,
      is_closed: false,
      is_anonymous: true,
      type: 'regular',
      allows_multiple_answers: false,
    },
    poll_answer: { poll_id: 'test-poll-1', user: from, option_ids: [0] },
    my_chat_member: {
      chat,
      from,
      date: now,
      old_chat_member: { user: from, status: 'left' },
      new_chat_member: { user: from, status: 'member' },
    },
    chat_member: {
      chat,
      from,
      date: now,
      old_chat_member: { user: from, status: 'left' },
      new_chat_member: { user: from, status: 'member' },
    },
    chat_join_request: { chat, from, user_chat_id: chat.id, date: now },
    message_reaction: {
      chat,
      message_id: 1,
      user: from,
      date: now,
      old_reaction: [],
      new_reaction: [{ type: 'emoji', emoji: '👍' }],
    },
    message_reaction_count: {
      chat,
      message_id: 1,
      date: now,
      reactions: [{ type: { type: 'emoji', emoji: '👍' }, total_count: 1 }],
    },
  };

  const body = bodies[eventType] ?? message;
  const key = eventType === '*' || eventType === 'unknown' ? 'message' : eventType;

  return {
    update_id: updateId,
    [key]: body,
    /** Non-standard marker: this update was generated by the gateway, not by Telegram. */
    gateway_test: true,
  };
}
